import image1 from "../assets/cards/image1.jpg";
import image2 from "../assets/cards/image2.jpg";
import image3 from "../assets/cards/image3.jpg";
import image4 from "../assets/cards/image4.jpg";
import image5 from "../assets/cards/image5.jpg";
import image6 from "../assets/cards/image6.jpg";
import image7 from "../assets/cards/image7.jpg";
import image8 from "../assets/cards/image8.jpg";
import image9 from "../assets/cards/image9.jpg";
import image10 from "../assets/cards/image10.jpg";
import image11 from "../assets/cards/image11.jpg";
import image12 from "../assets/cards/image12.jpg";

export const cardData = [
  { name: "The Magician", img: image1 },
  { name: "The High Priestess", img: image2 },
  { name: "The Empress", img: image3 },
  { name: "The Emperor", img: image4 },
  { name: "The Hierophant", img: image5 },
  { name: "The Lovers", img: image6 },
  { name: "The Chariot", img: image7 },
  { name: "Fortitude", img: image8 },
  { name: "The Hermit", img: image9 },
  { name: "Wheel Of Fortune", img: image10 },
  { name: "Justice", img: image11 },
  { name: "The Hanged Man", img: image12 }
];
const later = [
  { name: "Death", img: "path/to/image13.png" },
  { name: "Temperance", img: "path/to/image14.png" },
  { name: "The Devil", img: "path/to/image15.png" },
  { name: "The Tower", img: "path/to/image16.png" },
  { name: "The Star", img: "path/to/image17.png" },
  { name: "The Moon", img: "path/to/image18.png" },
  { name: "The Sun", img: "path/to/image19.png" },
  { name: "The Last Judgment", img: "path/to/image20.png" },
  { name: "The Fool", img: "path/to/image21.png" },
  { name: "The World", img: "path/to/image22.png" },
  { name: "Page of Wands", img: "path/to/image23.png" },
  { name: "Knight of Wands", img: "path/to/image24.png" },
  { name: "Queen of Wands", img: "path/to/image25.png" },
  { name: "King of Wands", img: "path/to/image26.png" },
  { name: "Ace of Wands", img: "path/to/image27.png" },
  { name: "Two of Wands", img: "path/to/image28.png" },
  { name: "Three of Wands", img: "path/to/image29.png" },
  { name: "Four of Wands", img: "path/to/image30.png" },
  { name: "Five of Wands", img: "path/to/image31.png" },
  { name: "Six of Wands", img: "path/to/image32.png" },
  { name: "Seven of Wands", img: "path/to/image33.png" },
  { name: "Eight of Wands", img: "path/to/image34.png" },
  { name: "Nine of Wands", img: "path/to/image35.png" },
  { name: "Ten of Wands", img: "path/to/image36.png" },
  { name: "Page of Cups", img: "path/to/image37.png" },
  { name: "Knight of Cups", img: "path/to/image38.png" },
  { name: "Queen of Cups", img: "path/to/image39.png" },
  { name: "King of Cups", img: "path/to/image40.png" },
  { name: "Ace of Cups", img: "path/to/image41.png" },
  { name: "Two of Cups", img: "path/to/image42.png" },
  { name: "Three of Cups", img: "path/to/image43.png" },
  { name: "Four of Cups", img: "path/to/image44.png" },
  { name: "Five of Cups", img: "path/to/image45.png" },
  { name: "Six of Cups", img: "path/to/image46.png" },
  { name: "Seven of Cups", img: "path/to/image47.png" },
  { name: "Eight of Cups", img: "path/to/image48.png" },
  { name: "Nine of Cups", img: "path/to/image49.png" },
  { name: "Ten of Cups", img: "path/to/image50.png" },
  { name: "Page of Pentacles", img: "path/to/image51.png" },
  { name: "Knight of Pentacles", img: "path/to/image52.png" },
  { name: "Queen of Pentacles", img: "path/to/image53.png" },
  { name: "King of Pentacles", img: "path/to/image54.png" },
  { name: "Ace of Pentacles", img: "path/to/image55.png" },
  { name: "Two of Pentacles", img: "path/to/image56.png" },
  { name: "Three of Pentacles", img: "path/to/image57.png" },
  { name: "Four of Pentacles", img: "path/to/image58.png" },
  { name: "Five of Pentacles", img: "path/to/image59.png" },
  { name: "Six of Pentacles", img: "path/to/image60.png" },
  { name: "Seven of Pentacles", img: "path/to/image61.png" },
  { name: "Eight of Pentacles", img: "path/to/image62.png" },
  { name: "Nine of Pentacles", img: "path/to/image63.png" },
  { name: "Ten of Pentacles", img: "path/to/image64.png" },
  { name: "Page of Swords", img: "path/to/image65.png" },
  { name: "Knight of Swords", img: "path/to/image66.png" },
  { name: "Queen of Swords", img: "path/to/image67.png" },
  { name: "King of Swords", img: "path/to/image68.png" },
  { name: "Ace of Swords", img: "path/to/image69.png" },
  { name: "Two of Swords", img: "path/to/image70.png" },
  { name: "Three of Swords", img: "path/to/image71.png" },
  { name: "Four of Swords", img: "path/to/image72.png" },
  { name: "Five of Swords", img: "path/to/image73.png" },
  { name: "Six of Swords", img: "path/to/image74.png" },
  { name: "Seven of Swords", img: "path/to/image75.png" },
  { name: "Eight of Swords", img: "path/to/image76.png" },
  { name: "Nine of Swords", img: "path/to/image77.png" },
  { name: "Ten of Swords", img: "path/to/image78.png" },
];
